num1=float(input("enter your first number"))
num1=int(num1)
num2=float(input("enter your second number"))
num2=int(num2)
num3=float(input("enter your third number"))
num3=int(num3)
num4=float(input("enter your fourth number"))
num4=int(num4)
total=int(num1+num2+num3+num4)
print("Thank you for entering your numbers their total is {0}.".format(total))
